=== geirs73/badebakken-brl/src/static/boligselskapsregler.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:r="urn:net.yxney.boligselskapsregler"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="urn:net.yxney.boligselskapsregler" elementFormDefault="qualified"
  xml:lang="no-NB" vc:minVersion="1.1">

  <!-- Dokument-rot ******************************************** -->

  <xs:element name="regelsett" type="r:typ_regelsett"/>

  <!-- Typer ****************************************************-->

  <xs:complexType name="typ_regelsett">
    <xs:sequence>
      <xs:element name="versjoner" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="versjon" type="r:typ_versjon" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="dokumenter" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="dokument" minOccurs="1" maxOccurs="unbounded" type="r:typ_dokument"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="typ_versjon">
    <xs:all>
      <xs:element name="vedtak" type="xs:normalizedString"/>
      <xs:element name="beskrivelse" type="xs:normalizedString" minOccurs="0"/>
      <xs:element name="endringer" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="endring" type="r:typ_endring" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="vedtaksdato" type="xs:date" use="optional"/>
    <xs:attribute name="ikrafttredelse" type="xs:date" use="required"/>
    <xs:attribute name="dokument-id" type="xs:IDREF" use="required"/>
  </xs:complexType>

  <xs:complexType name="typ_dokument">
    <xs:sequence>
      <xs:element name="tittel" minOccurs="0" maxOccurs="1">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element name="linje" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="introduksjon" minOccurs="0">
        <xs:complexType/>
      </xs:element>
      <xs:choice>
        <xs:element name="kapittel" type="r:typ_kapittel" maxOccurs="unbounded"/>
        <xs:element name="paragraf" type="r:typ_paragraf" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="paragraf-p" minOccurs="0" maxOccurs="unbounded" type="r:typ_setning"/>
      </xs:choice>
    </xs:sequence>
    <xs:attributeGroup ref="r:ag_dokument"/>
    <xs:attributeGroup ref="r:ag_id"/>
  </xs:complexType>

  <xs:complexType name="typ_endring">
    <xs:attribute name="handling" type="r:enm_handling" use="required"/>
    <xs:attribute name="referanse" type="xs:IDREF" use="required"/>
  </xs:complexType>

  <xs:complexType name="typ_kapittel">
    <xs:sequence>
      <xs:element name="tittel" type="xs:token" minOccurs="1"/>
      <xs:element name="paragraf" type="r:typ_paragraf" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="r:ag_regel"/>
    <xs:attributeGroup ref="r:ag_id"/>
  </xs:complexType>

  <xs:complexType name="typ_paragraf">
    <xs:sequence>
      <xs:element name="tittel" type="xs:token" minOccurs="0"/>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="p" type="r:typ_punktum" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="pf" type="r:typ_punktum_f" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="punktliste" type="r:typ_punktliste" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="1">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ledd" type="r:typ_ledd" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="ledd-p" minOccurs="0" maxOccurs="unbounded" type="r:typ_punktum"/>
          </xs:choice>
        </xs:choice>
      </xs:choice>
    </xs:sequence>
    <xs:attributeGroup ref="r:ag_regel"/>
    <xs:attributeGroup ref="r:ag_id"/>
  </xs:complexType>

  <!-- <xs:complexType name="typ_ledd-p"> <xs:sequence> <xs:simpleContent> <xs:restriction base="xs:string"> <xs:attribute name="foobar" />
  </xs:restriction> </xs:simpleContent> </xs:sequence> </xs:complexType> -->

  <xs:complexType name="typ_ledd">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="p" type="r:typ_punktum" minOccurs="0"/>
      <xs:element name="pf" type="r:typ_punktum_f" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="punktliste" type="r:typ_punktliste" minOccurs="0"/>
    </xs:choice>
    <xs:attributeGroup ref="r:ag_regel"/>
    <xs:attributeGroup ref="r:ag_id_optional"/>
  </xs:complexType>

  <xs:complexType name="typ_setning">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:attributeGroup ref="r:ag_id_optional"/>
        <xs:attributeGroup ref="r:ag_regel"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typ_formatert_setning">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="n" type="xs:string"/>
      <xs:element name="b" type="xs:string"/>
      <xs:element name="u" type="xs:string"/>
      <xs:element name="lov" type="r:typ_lovreferanse"/>
    </xs:choice>
    <xs:attributeGroup ref="r:ag_regel"/>
    <xs:attributeGroup ref="r:ag_id_optional"/>
    <xs:attribute name="sha1" type="xs:hexBinary"/>
  </xs:complexType>

  <xs:complexType name="typ_punktum">
    <xs:annotation>
      <xs:documentation>Punktum i lover er det samme som setninger i vanlig språkbruk. Forkortet til &lt;p&gt;</xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="r:typ_setning"/>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typ_punktum_f">
    <xs:annotation>
      <xs:documentation>Punktum i lover er det samme som setninger i vanlig språkbruk. Forkortet til &lt;p&gt;</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="r:typ_formatert_setning"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="typ_lovreferanse">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:attribute name="referanse" use="optional" type="xs:normalizedString"/>
        <xs:attribute name="lenke" use="optional" type="xs:anyURI"/>
        <xs:attribute name="type" use="required" type="r:enm_lovverk"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typ_punktliste">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="punkt" type="r:typ_punktum" maxOccurs="unbounded"/>
      <xs:element name="punkt-f" type="r:typ_formatert_setning" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute name="type" use="required" type="r:enm_punkter"/>
  </xs:complexType>

  <!-- Enumerasjoner ******************** -->

  <xs:simpleType name="enm_handling">
    <xs:restriction base="xs:normalizedString">
      <xs:enumeration value="sletting"/>
      <!-- <xs:enumeration value="redigering"/> -->
      <xs:enumeration value="tillegg"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="enm_punkter">
    <xs:restriction base="xs:normalizedString">
      <xs:enumeration value="strek"/>
      <xs:enumeration value="ordenstall"/>
      <xs:enumeration value="små-bokstaver"/>
      <xs:enumeration value="store-bokstaver"/>
      <xs:enumeration value="romertall"/>
    </xs:restriction>

  </xs:simpleType>

  <xs:simpleType name="enm_lovverk">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="brl-1960">
        <xs:annotation>
          <xs:documentation>Borettslagsloven 1960 https://lovdata.no/dokument/NLO/lov/1960-02-04-2</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="brl-2003">
        <xs:annotation>
          <xs:documentation>Borettslagsloven 2003 https://lovdata.no/dokument/NL/lov/2003-06-06-39</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="bbl-2003">
        <xs:annotation>
          <xs:documentation>Boligbyggelagsloven 2003 https://lovdata.no/dokument/NL/lov/2003-06-06-38</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="hfl-1991">
        <xs:annotation>
          <xs:documentation>Husstandsfellesskapsloven https://lovdata.no/dokument/NL/lov/1991-07-04-45</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="frl-1976">
        <xs:annotation>
          <xs:documentation>Forsinkelsesrenteloven https://lovdata.no/dokument/NL/lov/1976-12-17-100</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <!-- Attributter **************************************************** -->

  <xs:attributeGroup name="ag_permanent_id">
    <xs:attribute name="pid" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:hexBinary">
          <xs:length value="6"/>
          <!-- length in bytes, equals two digits in hexBinary of course -->
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="ag_id">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attributeGroup ref="r:ag_permanent_id"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ag_id_optional">
    <xs:attribute name="id" type="xs:ID" use="optional"/>
    <xs:attributeGroup ref="r:ag_permanent_id"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ag_nummerert_under">
    <xs:attribute name="nummerert-under" type="xs:boolean" use="optional" default="0">
      <xs:annotation>
        <xs:documentation> Slå av og på nummerering under nåværende element. 0 = av, 1 = på. </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="ag_nummerert">
    <xs:attributeGroup ref="r:ag_nummerert_under"/>
    <xs:attribute name="nummerert" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation> Slå av og på nummerering av nåværende element. 0 = av, 1 = på. </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="ag_dokument">
    <xs:attributeGroup ref="r:ag_nummerert_under"/>
    <xs:attribute name="gyldig-fra" type="xs:date" use="required"/>
    <xs:attribute name="gyldig-til" type="xs:date" use="optional" default="9999-01-01"/>
    <xs:attribute name="erstatter" type="xs:IDREFS"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ag_regel">
    <xs:attributeGroup ref="r:ag_nummerert"/>
    <xs:attribute name="gyldig-fra" type="xs:date" use="optional"/>
    <xs:attribute name="gyldig-til" type="xs:date" use="optional" default="9999-01-01"/>
    <xs:attribute name="erstatter" type="xs:IDREFS"/>
  </xs:attributeGroup>

</xs:schema>

=== geirs73/badebakken-brl/src/static/schema/eksempel.xml
<?xml version="1.0" encoding="UTF-8"?>
<regelsett
    xmlns="urn:no.badebakken.regelsett"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation="urn:no.badebakken.regelsett ../schema/boligselskapsregler.xsd"
>
  <dokument
      gyldig-fra="2023-01-01"
      id="id_bbc2d1504cf8400580b3b8b55e169f9f">
    <tittel>
      <linje />
    </tittel>
    <versjoner>
      <versjon vedtaksdato="2023-01-01">
        <vedtak />
        <endringer>
          <endring
              handling="tillegg"
              referanse="xxx" />
        </endringer>
      </versjon>
    </versjoner>
    <introduksjon />
    <kapittel id="a">
      <tittel />
      <paragraf id="id_f95a825347c54b3ea332581ca1c4e372">
        <tittel />
        <p id="xxx">
          <fremhevet />
          <understreket />
          <lov
              lenke=""
              type="borettslagslov-1960" />
        </p>
        <ledd id="id_5ec796361190478b87b4ab9e2df9f883">
          <p id="id_5fbdc5cd39144d55a1f197085987a1f1">
            <lov
                lenke=""
                type="borettslagslov-1960" />
          </p>
          <punktliste type="ordenstall">
            <punkt id="id_870b13d867f54ccda46fa987fd64cf34">
              <lov
                  lenke=""
                  type="borettslagslov-1960" />
            </punkt>
          </punktliste>
        </ledd>
      </paragraf>
      <paragraf id="id_a567de6162794de4ad5d645306b02eb4">
        <tittel>Foo</tittel>
        <p>3</p>
      </paragraf>
    </kapittel>
  </dokument>
</regelsett>
